{% set name = "mkdocs-markdownextradata-plugin" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 932f0752ddae3e08d9d1e30d5b7c703972af867149531f95930c3fad443600bc

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - mkdocs >=0.17
    - python >=3.5
    - setuptools

test:
  imports:
    - markdownextradata

about:
  home: https://github.com/rosscdh/mkdocs-markdownextradata-plugin/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A MkDocs plugin that injects the mkdocs.yml extra variables into the markdown template
  doc_url: http://www.mkdocs.org/user-guide/plugins/
  dev_url: https://github.com/rosscdh/mkdocs-markdownextradata-plugin/

extra:
  recipe-maintainers:
    - monaldoj
