travis:
  secure:
    BINSTAR_TOKEN: vzi7xcyjsDXyM/+/sWli00ixLorebqdrhkKD5lYVCJloFca/QyKiUh+UdfSWeQpK2XZa9mgnj9Fga5PUMA4o9B/RTyYAJIjseNOqj/XE1HT1Eyk3j/prRqh8Q0tRJHE2SLh0XLEqyjpEZ3v9N6UFzo0O/S4e1Soeu4RXaSvjdZVinytcTAyUdMf569WhFyD4xX7mWFqlcHh8Ar84UBlxxAjcQ8k2UkH58ORKcF76WhOWuxDCOGhU7LjNVO462lN/8qnYEuhaLUW/oCc622Y3v7t3V8ROMLe+90wDsW6dPtA7TQWL+HKqeyzprD6N7wuTzIaKQYam3mitR5tgOM6diy+RCcVPcQUnfEQohmTiUKj5+L+D+eYegIfyfgmnnk1wjKjxcCGM0nwtWt6C0E/UQoAKgBhhQ/OfYCLp4qyAKG69y/8+YrOJHqaeJorgz26KVJd2a4eUz0rTwlYSJHNPMsq/Nnohuy0d9EUmjstoaaDpRqu3qFzpeKOzXE5LWEPq2yQYDXUz+rInI4ZBeJcPTRkWegDJylRT+mrc0N3Tim4zIq+tNXF52/okg+mOlyEXyXU7hN6mfT028H2ro5O1vBxyAWKDNbqgPG2wB/PG0pjqndSJNs6Xj6/0pb+qLOz+QiLJ1+HcgfKPBGIP8s26lgP3HO3HmfABzJtgIY2DhK4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
